export const data = [
  {
    image: "https://robohash.org/atqueminussit.png?size=100x100&set=set1",
    name: "Daryl Cristofano",
    color: "Khaki",
    hex_color: "#627cdd",
    money: "$366.70",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/idverovelit.png?size=100x100&set=set1",
    name: "Gifford Brilleman",
    color: "Yellow",
    hex_color: "#dd6392",
    money: "$291.98",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quiadoloripsam.png?size=100x100&set=set1",
    name: "Edwin Strangwood",
    color: "Indigo",
    hex_color: "#149c21",
    money: "$671.01",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/atadipisciamet.png?size=100x100&set=set1",
    name: "Lorry Tourle",
    color: "Violet",
    hex_color: "#13fd24",
    money: "$559.65",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/iureutnon.png?size=100x100&set=set1",
    name: "Adan Howes",
    color: "Purple",
    hex_color: "#abe689",
    money: "$350.40",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/quiullamitaque.png?size=100x100&set=set1",
    name: "Nicolea Buttrum",
    color: "Mauv",
    hex_color: "#fdc574",
    money: "$155.76",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/repellendusplaceatquo.png?size=100x100&set=set1",
    name: "Barbe Birwhistle",
    color: "Blue",
    hex_color: "#4ab7b2",
    money: "$969.65",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sitmolestiasqui.png?size=100x100&set=set1",
    name: "Ardenia Tribell",
    color: "Purple",
    hex_color: "#24ac5e",
    money: "$420.34",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/voluptatumreprehenderitaliquam.png?size=100x100&set=set1",
    name: "Sybilla Scafe",
    color: "Pink",
    hex_color: "#37a9f3",
    money: "$523.52",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/molestiaeetducimus.png?size=100x100&set=set1",
    name: "Wyatan Praundl",
    color: "Crimson",
    hex_color: "#90b934",
    money: "$99.35",
    mobile: "Android 10, XOS 7.1",
  },
  {
    image: "https://robohash.org/blanditiissequimagni.png?size=100x100&set=set1",
    name: "Verena Liggett",
    color: "Violet",
    hex_color: "#da3b2f",
    money: "$617.35",
    mobile: "Nokia Asha software platform 1.1.1, up to 1.4",
  },
  {
    image: "https://robohash.org/temporibuseaut.png?size=100x100&set=set1",
    name: "Tomasina Roubeix",
    color: "Khaki",
    hex_color: "#fb91ef",
    money: "$186.50",
    mobile: "Android 1.5",
  },
  {
    image: "https://robohash.org/etrationevoluptatem.png?size=100x100&set=set1",
    name: "Alexei Paslow",
    color: "Teal",
    hex_color: "#4d3188",
    money: "$739.28",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/eligendiillopraesentium.png?size=100x100&set=set1",
    name: "Manon Peake",
    color: "Fuscia",
    hex_color: "#a0be88",
    money: "$554.80",
    mobile: "Android 2.3.4",
  },
  {
    image: "https://robohash.org/culpautofficia.png?size=100x100&set=set1",
    name: "Alvan Fender",
    color: "Yellow",
    hex_color: "#f45223",
    money: "$450.42",
    mobile: "Android 8.0, up to Android 9.0",
  },
  {
    image: "https://robohash.org/insuntomnis.png?size=100x100&set=set1",
    name: "Ines Glasser",
    color: "Purple",
    hex_color: "#d3ae0d",
    money: "$217.67",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/molestiaeharumaut.png?size=100x100&set=set1",
    name: "Marci McMurdo",
    color: "Mauv",
    hex_color: "#9b4b24",
    money: "$310.19",
    mobile: "Android 5.0, Flyme 4.5",
  },
  {
    image: "https://robohash.org/quiasaepedeleniti.png?size=100x100&set=set1",
    name: "Harriet Whitehair",
    color: "Maroon",
    hex_color: "#9f4f65",
    money: "$821.16",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/mollitiaullamnobis.png?size=100x100&set=set1",
    name: "Mohammed Ollerhead",
    color: "Crimson",
    hex_color: "#076d1a",
    money: "$654.34",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/laborequasimolestiae.png?size=100x100&set=set1",
    name: "Moina Cornilleau",
    color: "Purple",
    hex_color: "#15d577",
    money: "$660.59",
    mobile: "Microsoft Windows 10\r\nMicrosoft&hellip;",
  },
  {
    image: "https://robohash.org/voluptatumautvero.png?size=100x100&set=set1",
    name: "Romy Feld",
    color: "Pink",
    hex_color: "#77ca6c",
    money: "$549.89",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/aperiamidest.png?size=100x100&set=set1",
    name: "Mandie Ponnsett",
    color: "Indigo",
    hex_color: "#9a3b30",
    money: "$992.40",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/namdelenitinon.png?size=100x100&set=set1",
    name: "Nan Gurton",
    color: "Turquoise",
    hex_color: "#655d4a",
    money: "$846.95",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quaedoloremdignissimos.png?size=100x100&set=set1",
    name: "Kerrie Vanacci",
    color: "Aquamarine",
    hex_color: "#554535",
    money: "$19.58",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/utsintvoluptas.png?size=100x100&set=set1",
    name: "Skyler Lay",
    color: "Blue",
    hex_color: "#0f2a99",
    money: "$958.55",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/reprehenderitsuscipitet.png?size=100x100&set=set1",
    name: "Donaugh Cowely",
    color: "Puce",
    hex_color: "#820fcd",
    money: "$294.82",
    mobile: "Android 5.0",
  },
  {
    image: "https://robohash.org/voluptasdebitisnon.png?size=100x100&set=set1",
    name: "Ethelyn Eskrigge",
    color: "Purple",
    hex_color: "#50864c",
    money: "$408.82",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/abnonet.png?size=100x100&set=set1",
    name: "Bea Clymer",
    color: "Red",
    hex_color: "#4f4afd",
    money: "$598.56",
    mobile: "Android 10, Funtouch 10",
  },
  {
    image: "https://robohash.org/evenietadipiscicum.png?size=100x100&set=set1",
    name: "Coriss Gillford",
    color: "Aquamarine",
    hex_color: "#f8d911",
    money: "$378.12",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/praesentiummolestiasomnis.png?size=100x100&set=set1",
    name: "Trescha Orme",
    color: "Teal",
    hex_color: "#bd5fef",
    money: "$56.42",
    mobile: "Android 6.0.1, up to 7.1.2, MIUI 11",
  },
  {
    image: "https://robohash.org/providentrerumin.png?size=100x100&set=set1",
    name: "Greggory Stowers",
    color: "Puce",
    hex_color: "#598344",
    money: "$996.21",
    mobile: "Android 2.3, up to 4.0",
  },
  {
    image: "https://robohash.org/eiusvitaenihil.png?size=100x100&set=set1",
    name: "Eva Lowndes",
    color: "Violet",
    hex_color: "#3fa534",
    money: "$942.57",
    mobile: "Android 4.4.2, up to 5.0.2",
  },
  {
    image: "https://robohash.org/velitilloet.png?size=100x100&set=set1",
    name: "Nanette Gerant",
    color: "Yellow",
    hex_color: "#6d1cb4",
    money: "$778.94",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/quovoluptasin.png?size=100x100&set=set1",
    name: "Stafford Benmore",
    color: "Khaki",
    hex_color: "#d812fd",
    money: "$754.02",
    mobile: "Android 4.4",
  },
  {
    image: "https://robohash.org/quiaillumrerum.png?size=100x100&set=set1",
    name: "Timotheus Nelm",
    color: "Aquamarine",
    hex_color: "#faece8",
    money: "$420.99",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/aspernatureummagni.png?size=100x100&set=set1",
    name: "Forrester Ledger",
    color: "Purple",
    hex_color: "#cfe659",
    money: "$315.12",
    mobile: "Android 9.0, up to Android 11, MIUI 12",
  },
  {
    image: "https://robohash.org/idrepudiandaevoluptas.png?size=100x100&set=set1",
    name: "Devonne Gallahar",
    color: "Blue",
    hex_color: "#86fe10",
    money: "$608.03",
    mobile: "Android 6.1, ColorOS 3",
  },
  {
    image: "https://robohash.org/undeetratione.png?size=100x100&set=set1",
    name: "Jacynth Kentish",
    color: "Crimson",
    hex_color: "#800128",
    money: "$373.93",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/maioresquiquasi.png?size=100x100&set=set1",
    name: "Dorolice Vauter",
    color: "Red",
    hex_color: "#0e966e",
    money: "$76.84",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/ipsaofficiarerum.png?size=100x100&set=set1",
    name: "Dorise Eayres",
    color: "Mauv",
    hex_color: "#5f343c",
    money: "$875.73",
    mobile: "Proprietary OS",
  },
  {
    image: "https://robohash.org/eaquesuscipitlaborum.png?size=100x100&set=set1",
    name: "Garold Mariette",
    color: "Yellow",
    hex_color: "#10891c",
    money: "$413.17",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/odioitaqueaut.png?size=100x100&set=set1",
    name: "Lazarus Hayford",
    color: "Yellow",
    hex_color: "#823a54",
    money: "$940.77",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/placeatbeataereiciendis.png?size=100x100&set=set1",
    name: "Fulvia Bocke",
    color: "Violet",
    hex_color: "#8985b1",
    money: "$942.30",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/itaqueharumvoluptatem.png?size=100x100&set=set1",
    name: "Nani Fishleigh",
    color: "Violet",
    hex_color: "#c3ce61",
    money: "$784.96",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/nonquosconsequatur.png?size=100x100&set=set1",
    name: "Virginia Clerc",
    color: "Violet",
    hex_color: "#c948d7",
    money: "$979.31",
    mobile: "Microsoft Windows Mobile 6.1 Professional",
  },
  {
    image: "https://robohash.org/sedvitaererum.png?size=100x100&set=set1",
    name: "Dayle Drayn",
    color: "Blue",
    hex_color: "#5b1cb3",
    money: "$88.94",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/auteiusut.png?size=100x100&set=set1",
    name: "Henderson Odgaard",
    color: "Fuscia",
    hex_color: "#7bc17f",
    money: "$721.58",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/aliquamdolorconsectetur.png?size=100x100&set=set1",
    name: "Zarah Edison",
    color: "Indigo",
    hex_color: "#02c476",
    money: "$149.56",
    mobile: "Android 2.2",
  },
  {
    image: "https://robohash.org/inestet.png?size=100x100&set=set1",
    name: "Michel Fricker",
    color: "Maroon",
    hex_color: "#014720",
    money: "$143.37",
    mobile: "Android 6.0.1, up to 7.1.2, MIUI 11",
  },
  {
    image: "https://robohash.org/etfugiatdoloremque.png?size=100x100&set=set1",
    name: "Cecilla Lopes",
    color: "Indigo",
    hex_color: "#687c69",
    money: "$242.46",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nonvelet.png?size=100x100&set=set1",
    name: "Link Northridge",
    color: "Fuscia",
    hex_color: "#0bd129",
    money: "$600.07",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/voluptateseaaccusantium.png?size=100x100&set=set1",
    name: "Zedekiah Babalola",
    color: "Indigo",
    hex_color: "#1884e3",
    money: "$607.63",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/esseenimasperiores.png?size=100x100&set=set1",
    name: "Kinny Bonwick",
    color: "Red",
    hex_color: "#4621d0",
    money: "$901.42",
    mobile: "Android 1.5, Sense UI",
  },
  {
    image: "https://robohash.org/quiavoluptasvoluptatibus.png?size=100x100&set=set1",
    name: "Lina Shackleton",
    color: "Aquamarine",
    hex_color: "#29f2ee",
    money: "$136.44",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/eligendidoloremculpa.png?size=100x100&set=set1",
    name: "Euell Pottle",
    color: "Teal",
    hex_color: "#1cd031",
    money: "$496.84",
    mobile: "Android 4.4, up to 5.0.2, TouchWiz UI",
  },
  {
    image: "https://robohash.org/quaeratnemoaspernatur.png?size=100x100&set=set1",
    name: "Georgina Casoni",
    color: "Khaki",
    hex_color: "#7951be",
    money: "$262.08",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/doloresofficiisvelit.png?size=100x100&set=set1",
    name: "Lenard Gurner",
    color: "Purple",
    hex_color: "#68f9f5",
    money: "$726.72",
    mobile: "Android 9.0, Funtouch 9",
  },
  {
    image: "https://robohash.org/sitteneturvoluptatem.png?size=100x100&set=set1",
    name: "Currey Seefus",
    color: "Aquamarine",
    hex_color: "#2ea244",
    money: "$985.36",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etblanditiisqui.png?size=100x100&set=set1",
    name: "Terza Mingaud",
    color: "Goldenrod",
    hex_color: "#a67f8c",
    money: "$588.94",
    mobile: "Android 9.0, EMUI 9.1",
  },
  {
    image: "https://robohash.org/sapientefugiatut.png?size=100x100&set=set1",
    name: "Marlo Ivoshin",
    color: "Goldenrod",
    hex_color: "#2c0843",
    money: "$172.12",
    mobile: "Android 9.0, up to Android 10, Magic UI 2.1",
  },
  {
    image: "https://robohash.org/distinctioatqueid.png?size=100x100&set=set1",
    name: "Merna Praton",
    color: "Blue",
    hex_color: "#f19bd8",
    money: "$249.90",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/voluptateseosexplicabo.png?size=100x100&set=set1",
    name: "Katrine Knibley",
    color: "Khaki",
    hex_color: "#37d8f3",
    money: "$723.51",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/praesentiumnemofugiat.png?size=100x100&set=set1",
    name: "Mikaela Spick",
    color: "Fuscia",
    hex_color: "#ec2675",
    money: "$168.54",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/consequaturquodratione.png?size=100x100&set=set1",
    name: "Alaine Lapley",
    color: "Khaki",
    hex_color: "#ef36cd",
    money: "$219.51",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/aspernaturetet.png?size=100x100&set=set1",
    name: "Pierce Whyte",
    color: "Orange",
    hex_color: "#395cdb",
    money: "$60.00",
    mobile: "Microsoft Windows Mobile 6.1 Professional",
  },
  {
    image: "https://robohash.org/quiaetnulla.png?size=100x100&set=set1",
    name: "Almire Hizir",
    color: "Teal",
    hex_color: "#0948e6",
    money: "$109.01",
    mobile: "Android 4.4, up to 5.0.2, TouchWiz UI",
  },
  {
    image: "https://robohash.org/doloribusvoluptatumsuscipit.png?size=100x100&set=set1",
    name: "Brandais Chaldecott",
    color: "Blue",
    hex_color: "#77e3c4",
    money: "$894.50",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/blanditiisquiapraesentium.png?size=100x100&set=set1",
    name: "Tadio Sallarie",
    color: "Khaki",
    hex_color: "#a730e4",
    money: "$789.80",
    mobile: "Android 4.1",
  },
  {
    image: "https://robohash.org/reiciendisetdoloribus.png?size=100x100&set=set1",
    name: "Gwenni Le Prevost",
    color: "Turquoise",
    hex_color: "#03e264",
    money: "$576.89",
    mobile: "Android 4.4.4, up to 6.0",
  },
  {
    image: "https://robohash.org/etdolorsit.png?size=100x100&set=set1",
    name: "Corinne Leedal",
    color: "Crimson",
    hex_color: "#657d4f",
    money: "$214.25",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quiquioptio.png?size=100x100&set=set1",
    name: "Natasha Ashfield",
    color: "Khaki",
    hex_color: "#a234ff",
    money: "$472.78",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/sunteosut.png?size=100x100&set=set1",
    name: "Dorette Turpie",
    color: "Maroon",
    hex_color: "#7d3d1f",
    money: "$806.01",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/doloreveromodi.png?size=100x100&set=set1",
    name: "Charlotta Reskelly",
    color: "Green",
    hex_color: "#86af14",
    money: "$174.85",
    mobile: "Android 2.1",
  },
  {
    image: "https://robohash.org/dolorquaeimpedit.png?size=100x100&set=set1",
    name: "Batholomew Crosio",
    color: "Red",
    hex_color: "#15837a",
    money: "$339.27",
    mobile: "Android 4.4.2, up to 6.0, Sense UI 6",
  },
  {
    image: "https://robohash.org/autanimisunt.png?size=100x100&set=set1",
    name: "Eben Skeats",
    color: "Crimson",
    hex_color: "#a53d3c",
    money: "$101.12",
    mobile: "Proprietary OS",
  },
  {
    image: "https://robohash.org/perspiciatisestqui.png?size=100x100&set=set1",
    name: "Frayda Haddrell",
    color: "Puce",
    hex_color: "#f45289",
    money: "$365.27",
    mobile: "Microsoft Windows Mobile 6.5.3 Professional",
  },
  {
    image: "https://robohash.org/voluptatempariaturaliquam.png?size=100x100&set=set1",
    name: "Fransisco Salvati",
    color: "Khaki",
    hex_color: "#425613",
    money: "$556.03",
    mobile: "Microsoft Windows Phone 7",
  },
  {
    image: "https://robohash.org/nihiletautem.png?size=100x100&set=set1",
    name: "Hardy McCloughlin",
    color: "Indigo",
    hex_color: "#8b95f9",
    money: "$541.64",
    mobile: "Microsoft Windows Phone 8, up to 8.1",
  },
  {
    image: "https://robohash.org/estautemadipisci.png?size=100x100&set=set1",
    name: "Loise Dilston",
    color: "Blue",
    hex_color: "#e30ad7",
    money: "$412.53",
    mobile: "Android 2.1, up to 2.2",
  },
  {
    image: "https://robohash.org/quiatet.png?size=100x100&set=set1",
    name: "Pansie Danilovic",
    color: "Violet",
    hex_color: "#54eac3",
    money: "$369.43",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/doloremsaepea.png?size=100x100&set=set1",
    name: "Somerset Rome",
    color: "Goldenrod",
    hex_color: "#6d1fb8",
    money: "$961.49",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/voluptateidmodi.png?size=100x100&set=set1",
    name: "Audrey Sturm",
    color: "Goldenrod",
    hex_color: "#974a66",
    money: "$785.99",
    mobile: "Android 4.0",
  },
  {
    image: "https://robohash.org/auttemporibusquas.png?size=100x100&set=set1",
    name: "Romy Seiler",
    color: "Indigo",
    hex_color: "#22d315",
    money: "$574.07",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/exdoloresvoluptas.png?size=100x100&set=set1",
    name: "Flossy Kelberer",
    color: "Maroon",
    hex_color: "#b71e54",
    money: "$551.74",
    mobile: "Android 4.4.4, MIUI 6.0",
  },
  {
    image: "https://robohash.org/liberonobisnostrum.png?size=100x100&set=set1",
    name: "Jannelle O'Rowane",
    color: "Violet",
    hex_color: "#0155d9",
    money: "$791.66",
    mobile: "Android 8.1, EMUI 8.2",
  },
  {
    image: "https://robohash.org/noninventorequo.png?size=100x100&set=set1",
    name: "Clyve Kaes",
    color: "Puce",
    hex_color: "#d859f1",
    money: "$994.82",
    mobile: "Symbian OS 9.3, S60 rel. 3.2",
  },
  {
    image: "https://robohash.org/officiaconsecteturtenetur.png?size=100x100&set=set1",
    name: "Claudell Nuccitelli",
    color: "Goldenrod",
    hex_color: "#232b8a",
    money: "$128.27",
    mobile: "Android 10, IQOO UI 1.0",
  },
  {
    image: "https://robohash.org/doloresrepellatmolestiae.png?size=100x100&set=set1",
    name: "Rowena Burniston",
    color: "Green",
    hex_color: "#421472",
    money: "$42.54",
    mobile: "Android 4.4.2, up to 5.0.2",
  },
  {
    image: "https://robohash.org/voluptasomnisexpedita.png?size=100x100&set=set1",
    name: "Anastassia Parlour",
    color: "Turquoise",
    hex_color: "#ac34c1",
    money: "$257.18",
    mobile: "Android 4.3, up to 5.0, Sense UI 5.5",
  },
  {
    image: "https://robohash.org/architectoautdolorem.png?size=100x100&set=set1",
    name: "Winn Dalrymple",
    color: "Mauv",
    hex_color: "#a8854a",
    money: "$61.82",
    mobile: "Android 4.4.4, Sense UI",
  },
  {
    image: "https://robohash.org/similiquebeataenecessitatibus.png?size=100x100&set=set1",
    name: "Phil Neath",
    color: "Blue",
    hex_color: "#e8364c",
    money: "$409.21",
    mobile: "Android 4.4",
  },
  {
    image: "https://robohash.org/enimetet.png?size=100x100&set=set1",
    name: "Zahara Switzer",
    color: "Teal",
    hex_color: "#1dc16f",
    money: "$864.86",
    mobile: "Android 4.4.4, TouchWiz UI",
  },
  {
    image: "https://robohash.org/sitdoloresint.png?size=100x100&set=set1",
    name: "Elianore Jeffreys",
    color: "Purple",
    hex_color: "#962c06",
    money: "$228.86",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/laudantiumremvoluptatibus.png?size=100x100&set=set1",
    name: "Tricia Toone",
    color: "Blue",
    hex_color: "#51eb44",
    money: "$518.77",
    mobile: "Android 4.1",
  },
  {
    image: "https://robohash.org/beataeofficiisquod.png?size=100x100&set=set1",
    name: "Rufus Fuzzard",
    color: "Violet",
    hex_color: "#ee1ca4",
    money: "$776.42",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/eacommodireiciendis.png?size=100x100&set=set1",
    name: "Alley Tungate",
    color: "Puce",
    hex_color: "#ffd419",
    money: "$112.13",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etenimveniam.png?size=100x100&set=set1",
    name: "Kendal Groven",
    color: "Khaki",
    hex_color: "#1b313d",
    money: "$914.64",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/illumvoluptassit.png?size=100x100&set=set1",
    name: "Tann Sabie",
    color: "Yellow",
    hex_color: "#2c1b86",
    money: "$184.99",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/fugaestnumquam.png?size=100x100&set=set1",
    name: "Dav Lamacraft",
    color: "Red",
    hex_color: "#bedce0",
    money: "$201.78",
    mobile: "Android 2.3",
  },
  {
    image: "https://robohash.org/ipsamlaboriosamut.png?size=100x100&set=set1",
    name: "Quent Sinnock",
    color: "Yellow",
    hex_color: "#23422c",
    money: "$991.55",
    mobile: "Android 2.3",
  },
  {
    image: "https://robohash.org/laudantiumexercitationemaliquid.png?size=100x100&set=set1",
    name: "Tiffanie Burk",
    color: "Fuscia",
    hex_color: "#bb2835",
    money: "$394.14",
    mobile: "Android 5.0, up to 6.0, ZenUI",
  },
  {
    image: "https://robohash.org/quasicommodiasperiores.png?size=100x100&set=set1",
    name: "Onofredo Barkhouse",
    color: "Blue",
    hex_color: "#62f60e",
    money: "$663.01",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etvoluptatemconsequatur.png?size=100x100&set=set1",
    name: "Berna Abrey",
    color: "Purple",
    hex_color: "#c28b63",
    money: "$172.87",
    mobile: "Android 4.4.4, up to 6.0",
  },
  {
    image: "https://robohash.org/autofficiisrem.png?size=100x100&set=set1",
    name: "Dolli Reihm",
    color: "Goldenrod",
    hex_color: "#0ff097",
    money: "$786.67",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/possimuseaplaceat.png?size=100x100&set=set1",
    name: "Gordon Dell Casa",
    color: "Indigo",
    hex_color: "#f6dd18",
    money: "$334.62",
    mobile: "Android 2.3.7",
  },
  {
    image: "https://robohash.org/voluptatemreprehenderitnisi.png?size=100x100&set=set1",
    name: "Otis Huntingdon",
    color: "Blue",
    hex_color: "#a85e67",
    money: "$790.11",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/placeatvoluptatemfugit.png?size=100x100&set=set1",
    name: "Boonie De la Harpe",
    color: "Puce",
    hex_color: "#4e19bb",
    money: "$458.50",
    mobile: "Symbian OS 9.1, Series 60 UI",
  },
  {
    image: "https://robohash.org/quodquiaautem.png?size=100x100&set=set1",
    name: "Aron Traher",
    color: "Blue",
    hex_color: "#bc8ea6",
    money: "$35.69",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/repellatsedsed.png?size=100x100&set=set1",
    name: "Merrel Aldcorn",
    color: "Orange",
    hex_color: "#af5ada",
    money: "$878.74",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/omnisdictaquae.png?size=100x100&set=set1",
    name: "Cullin Routhorn",
    color: "Teal",
    hex_color: "#84ec6a",
    money: "$550.08",
    mobile: "Android 2.2",
  },
  {
    image: "https://robohash.org/voluptatibusdoloremlaboriosam.png?size=100x100&set=set1",
    name: "Arabele Ealles",
    color: "Green",
    hex_color: "#e2b843",
    money: "$965.69",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/illorerumminus.png?size=100x100&set=set1",
    name: "Shermie Jessup",
    color: "Red",
    hex_color: "#efe13d",
    money: "$321.22",
    mobile: "BlackBerry Tablet 2.0",
  },
  {
    image: "https://robohash.org/aadipiscivelit.png?size=100x100&set=set1",
    name: "Sheffy Sterricker",
    color: "Crimson",
    hex_color: "#96e8bd",
    money: "$602.61",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/aspernaturiustoa.png?size=100x100&set=set1",
    name: "Theodosia Wolstencroft",
    color: "Fuscia",
    hex_color: "#4e1ed5",
    money: "$433.39",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/voluptateutest.png?size=100x100&set=set1",
    name: "Vernen Bausor",
    color: "Khaki",
    hex_color: "#e9e469",
    money: "$123.91",
    mobile: "Android 8.0, up to Android 10, Android One",
  },
  {
    image: "https://robohash.org/ducimusetnesciunt.png?size=100x100&set=set1",
    name: "Annabela Heinsh",
    color: "Red",
    hex_color: "#8f303b",
    money: "$245.24",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/sapientearchitectovero.png?size=100x100&set=set1",
    name: "Federico Bondy",
    color: "Aquamarine",
    hex_color: "#34effc",
    money: "$649.23",
    mobile: "Android 9.0, ColorOS 6",
  },
  {
    image: "https://robohash.org/doloreveroomnis.png?size=100x100&set=set1",
    name: "Kimbra Kiebes",
    color: "Puce",
    hex_color: "#c3df00",
    money: "$822.89",
    mobile: "Android 6.1, nubia UI 4",
  },
  {
    image: "https://robohash.org/necessitatibusmolestiaedolorem.png?size=100x100&set=set1",
    name: "Kathe Halsey",
    color: "Violet",
    hex_color: "#adbfb0",
    money: "$681.47",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/cumquisquamfuga.png?size=100x100&set=set1",
    name: "Cammie Faherty",
    color: "Khaki",
    hex_color: "#8c6d57",
    money: "$28.59",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/earumnequererum.png?size=100x100&set=set1",
    name: "Michaela Bitchener",
    color: "Violet",
    hex_color: "#49e924",
    money: "$796.11",
    mobile: "Android 4.0.4",
  },
  {
    image: "https://robohash.org/eaconsequaturomnis.png?size=100x100&set=set1",
    name: "Isidore Cadell",
    color: "Violet",
    hex_color: "#b9259c",
    money: "$233.21",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/omnissaepeenim.png?size=100x100&set=set1",
    name: "Reba Barts",
    color: "Mauv",
    hex_color: "#41b5ff",
    money: "$938.22",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quiquoea.png?size=100x100&set=set1",
    name: "Elena Isaacson",
    color: "Purple",
    hex_color: "#1efde2",
    money: "$717.76",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/quiexplicabodolores.png?size=100x100&set=set1",
    name: "Leora Miskin",
    color: "Purple",
    hex_color: "#b5cdae",
    money: "$98.58",
    mobile: "Android 4.0",
  },
  {
    image: "https://robohash.org/veritatiseanecessitatibus.png?size=100x100&set=set1",
    name: "Thomasin Roote",
    color: "Violet",
    hex_color: "#c384e4",
    money: "$728.26",
    mobile: "Android 6.0.1, up to Android 8.0",
  },
  {
    image: "https://robohash.org/quianameius.png?size=100x100&set=set1",
    name: "Theodosia Dene",
    color: "Mauv",
    hex_color: "#7bab01",
    money: "$841.72",
    mobile: "Android 8.1, Funtouch 4",
  },
  {
    image: "https://robohash.org/velitrepudiandaeet.png?size=100x100&set=set1",
    name: "Manon Eginton",
    color: "Khaki",
    hex_color: "#fd507c",
    money: "$803.04",
    mobile: "Proprietary OS",
  },
  {
    image: "https://robohash.org/inventoreesseaspernatur.png?size=100x100&set=set1",
    name: "Angelina Dobrovolny",
    color: "Blue",
    hex_color: "#4dfcfd",
    money: "$274.58",
    mobile: "Android 4.4, EMUI 3",
  },
  {
    image: "https://robohash.org/etvoluptasquia.png?size=100x100&set=set1",
    name: "Monique Willgrass",
    color: "Maroon",
    hex_color: "#9479e5",
    money: "$357.82",
    mobile: "Android 2.3.3, up to 3.2, Sense UI",
  },
  {
    image: "https://robohash.org/quiillumasperiores.png?size=100x100&set=set1",
    name: "Lorelei Mettrick",
    color: "Indigo",
    hex_color: "#8642ae",
    money: "$343.09",
    mobile: "Android 8.1, planned upgrade to 9.0",
  },
  {
    image: "https://robohash.org/excepturimagniprovident.png?size=100x100&set=set1",
    name: "Loise Elrick",
    color: "Violet",
    hex_color: "#45a88f",
    money: "$66.50",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/aliquidomnisin.png?size=100x100&set=set1",
    name: "Car Brumfitt",
    color: "Maroon",
    hex_color: "#985628",
    money: "$380.57",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/officiaconsequaturest.png?size=100x100&set=set1",
    name: "Ancell Jerratsch",
    color: "Khaki",
    hex_color: "#00c9df",
    money: "$887.91",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/sedodiomaiores.png?size=100x100&set=set1",
    name: "Bobbee Giacaponi",
    color: "Turquoise",
    hex_color: "#12bffb",
    money: "$106.96",
    mobile: "Android 4.3, up to 4.4",
  },
  {
    image: "https://robohash.org/odioetid.png?size=100x100&set=set1",
    name: "Anita Gianneschi",
    color: "Orange",
    hex_color: "#9c9643",
    money: "$704.79",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/sitinvoluptas.png?size=100x100&set=set1",
    name: "Ynez Hackford",
    color: "Purple",
    hex_color: "#0e01f0",
    money: "$709.75",
    mobile: "Android 9.0, up to Android 10, Magic UI 4.0",
  },
  {
    image: "https://robohash.org/omnisporrodolores.png?size=100x100&set=set1",
    name: "Ava Lorait",
    color: "Mauv",
    hex_color: "#f5c924",
    money: "$893.29",
    mobile: "Android 10, ColorOS 7.2",
  },
  {
    image: "https://robohash.org/utearumdebitis.png?size=100x100&set=set1",
    name: "Daveen Paskin",
    color: "Red",
    hex_color: "#e8f799",
    money: "$151.10",
    mobile: "Android 8.0, EMUI 8",
  },
  {
    image: "https://robohash.org/modinesciuntnon.png?size=100x100&set=set1",
    name: "Malvin Agglione",
    color: "Violet",
    hex_color: "#4806d4",
    money: "$868.94",
    mobile: "Android 7.1.1, up to Android 9.0",
  },
  {
    image: "https://robohash.org/quoautemmaxime.png?size=100x100&set=set1",
    name: "Kinna Parker",
    color: "Blue",
    hex_color: "#f75aa3",
    money: "$314.43",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/repellendusliberoest.png?size=100x100&set=set1",
    name: "Brigitte Orth",
    color: "Purple",
    hex_color: "#e06871",
    money: "$77.20",
    mobile: "Android 8.1, up to Android 11, OxygenOS 11",
  },
  {
    image: "https://robohash.org/laudantiumaccusamusiusto.png?size=100x100&set=set1",
    name: "Jules Eddis",
    color: "Aquamarine",
    hex_color: "#f61aba",
    money: "$761.67",
    mobile: "Android 5.0",
  },
  {
    image: "https://robohash.org/ipsamisteet.png?size=100x100&set=set1",
    name: "Ulrike Sacase",
    color: "Blue",
    hex_color: "#703ffd",
    money: "$420.28",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/ipsalaboreomnis.png?size=100x100&set=set1",
    name: "Nehemiah Wassung",
    color: "Maroon",
    hex_color: "#07bd2d",
    money: "$935.11",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/mollitiaaccusamusitaque.png?size=100x100&set=set1",
    name: "Hart Elcoate",
    color: "Yellow",
    hex_color: "#218f84",
    money: "$201.64",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sintvoluptatesqui.png?size=100x100&set=set1",
    name: "Hannis Rowberry",
    color: "Blue",
    hex_color: "#3defff",
    money: "$890.67",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/inventorequibusdamratione.png?size=100x100&set=set1",
    name: "Brandyn Hindrich",
    color: "Mauv",
    hex_color: "#66289c",
    money: "$855.07",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etsolutavoluptatem.png?size=100x100&set=set1",
    name: "Tally Barnwell",
    color: "Violet",
    hex_color: "#bdbb5c",
    money: "$663.87",
    mobile: "Android OS",
  },
  {
    image: "https://robohash.org/inciduntnequenon.png?size=100x100&set=set1",
    name: "Juana Scogings",
    color: "Teal",
    hex_color: "#e8824c",
    money: "$616.66",
    mobile: "Microsoft Windows Phone 8, up to 8.1.1",
  },
  {
    image: "https://robohash.org/autmagniest.png?size=100x100&set=set1",
    name: "Livvyy Schruur",
    color: "Orange",
    hex_color: "#11b5c9",
    money: "$933.65",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/eossunthic.png?size=100x100&set=set1",
    name: "Torrey Benzing",
    color: "Green",
    hex_color: "#83cc69",
    money: "$452.76",
    mobile: "Android 8.1 Oreo",
  },
  {
    image: "https://robohash.org/voluptatemconsequunturvel.png?size=100x100&set=set1",
    name: "Ogdon Cawood",
    color: "Khaki",
    hex_color: "#4b0f91",
    money: "$672.38",
    mobile: "Android 4.0",
  },
  {
    image: "https://robohash.org/liberolaboriosamarchitecto.png?size=100x100&set=set1",
    name: "William Weiss",
    color: "Fuscia",
    hex_color: "#7d3788",
    money: "$801.06",
    mobile: "Android 10",
  },
  {
    image: "https://robohash.org/autmolestiaesed.png?size=100x100&set=set1",
    name: "Edik Sygroves",
    color: "Purple",
    hex_color: "#02f653",
    money: "$21.05",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/odioquodeius.png?size=100x100&set=set1",
    name: "Gillan Challin",
    color: "Yellow",
    hex_color: "#d918b4",
    money: "$943.31",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/doloresexpeditaesse.png?size=100x100&set=set1",
    name: "Aldis Breedy",
    color: "Khaki",
    hex_color: "#b32250",
    money: "$46.31",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etundeipsum.png?size=100x100&set=set1",
    name: "Carling Gosford",
    color: "Khaki",
    hex_color: "#cc9720",
    money: "$15.27",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/accusamuslaboriosameveniet.png?size=100x100&set=set1",
    name: "Vite Jacquemot",
    color: "Khaki",
    hex_color: "#daf730",
    money: "$878.53",
    mobile: "BlackBerry OS",
  },
  {
    image: "https://robohash.org/porronumquamaccusantium.png?size=100x100&set=set1",
    name: "Renell Fulop",
    color: "Pink",
    hex_color: "#577278",
    money: "$427.07",
    mobile: "Android 8.0, EMUI 8",
  },
  {
    image: "https://robohash.org/autemestvoluptatem.png?size=100x100&set=set1",
    name: "Flin Galpen",
    color: "Blue",
    hex_color: "#8aa084",
    money: "$84.17",
    mobile: "Android 5.0",
  },
  {
    image: "https://robohash.org/atqueesseut.png?size=100x100&set=set1",
    name: "Avery Winkle",
    color: "Blue",
    hex_color: "#7b8116",
    money: "$533.30",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/exquasifacilis.png?size=100x100&set=set1",
    name: "Blythe Creser",
    color: "Maroon",
    hex_color: "#2c564a",
    money: "$553.26",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/occaecatiundetotam.png?size=100x100&set=set1",
    name: "Sybil Cocker",
    color: "Maroon",
    hex_color: "#cf05a7",
    money: "$984.76",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/perferendisautearum.png?size=100x100&set=set1",
    name: "Jephthah Gilleon",
    color: "Turquoise",
    hex_color: "#9aa576",
    money: "$164.31",
    mobile: "Android 10, Magic UI 3",
  },
  {
    image: "https://robohash.org/placeatculpaet.png?size=100x100&set=set1",
    name: "Courtney Simakov",
    color: "Puce",
    hex_color: "#af67c6",
    money: "$487.43",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/exercitationemeaqueest.png?size=100x100&set=set1",
    name: "Matt Eacle",
    color: "Pink",
    hex_color: "#258c3f",
    money: "$33.66",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/odiomolestiaequi.png?size=100x100&set=set1",
    name: "Towney Marsham",
    color: "Red",
    hex_color: "#ef1b65",
    money: "$163.19",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/quimaximepraesentium.png?size=100x100&set=set1",
    name: "Leonardo Wickliffe",
    color: "Green",
    hex_color: "#81ea4f",
    money: "$257.07",
    mobile: "Android 10",
  },
  {
    image: "https://robohash.org/aliasetest.png?size=100x100&set=set1",
    name: "Johannah Huge",
    color: "Fuscia",
    hex_color: "#0e43ab",
    money: "$569.96",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/aliquidfugiateos.png?size=100x100&set=set1",
    name: "Demetri Palphreyman",
    color: "Maroon",
    hex_color: "#5a1c8f",
    money: "$79.24",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/eumteneturcumque.png?size=100x100&set=set1",
    name: "Salvidor Souch",
    color: "Violet",
    hex_color: "#5eb333",
    money: "$897.54",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/odioilloaut.png?size=100x100&set=set1",
    name: "Aguste Fransman",
    color: "Blue",
    hex_color: "#2234f2",
    money: "$261.75",
    mobile: "Microsoft Windows Phone 8.1",
  },
  {
    image: "https://robohash.org/consecteturmaioresaut.png?size=100x100&set=set1",
    name: "Baryram Kynvin",
    color: "Crimson",
    hex_color: "#3570a8",
    money: "$686.49",
    mobile: "Android 10, EMUI 11, no Google Play Services",
  },
  {
    image: "https://robohash.org/nonomnisvel.png?size=100x100&set=set1",
    name: "Cece Coggill",
    color: "Fuscia",
    hex_color: "#bb965e",
    money: "$512.68",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/perferendisreprehenderitatque.png?size=100x100&set=set1",
    name: "Dannie Triggs",
    color: "Crimson",
    hex_color: "#d6afb3",
    money: "$977.85",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sitomnisut.png?size=100x100&set=set1",
    name: "Davide Herkess",
    color: "Pink",
    hex_color: "#3bb01b",
    money: "$405.95",
    mobile: "Android 5.2, MiFavor 3",
  },
  {
    image: "https://robohash.org/optioarchitectovoluptas.png?size=100x100&set=set1",
    name: "Babara Ridett",
    color: "Khaki",
    hex_color: "#45ca34",
    money: "$916.90",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/occaecatietsed.png?size=100x100&set=set1",
    name: "Ferne Gerriet",
    color: "Fuscia",
    hex_color: "#5ca28b",
    money: "$562.49",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/officiisdoloremhic.png?size=100x100&set=set1",
    name: "Silvanus Annes",
    color: "Violet",
    hex_color: "#2a2b9a",
    money: "$437.36",
    mobile: "Android 10, EMUI 10, no Google Play Services",
  },
  {
    image: "https://robohash.org/natusmolestiaevero.png?size=100x100&set=set1",
    name: "Clim Lampen",
    color: "Pink",
    hex_color: "#7dd9d6",
    money: "$602.54",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/laboriosamoptiosaepe.png?size=100x100&set=set1",
    name: "Alexina Jiroutka",
    color: "Yellow",
    hex_color: "#097eec",
    money: "$44.27",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/voluptatessedin.png?size=100x100&set=set1",
    name: "Cathie Corking",
    color: "Orange",
    hex_color: "#82f370",
    money: "$470.58",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/illoveroomnis.png?size=100x100&set=set1",
    name: "Costa Walkowski",
    color: "Orange",
    hex_color: "#2b17be",
    money: "$431.66",
    mobile: "Android 6.0, EMUI 4.1 Mini",
  },
  {
    image: "https://robohash.org/autvoluptatemet.png?size=100x100&set=set1",
    name: "Hendrika Dearl",
    color: "Teal",
    hex_color: "#e6d865",
    money: "$173.38",
    mobile: "HP webOS 2.1",
  },
  {
    image: "https://robohash.org/auteligendiminima.png?size=100x100&set=set1",
    name: "Halie Posten",
    color: "Blue",
    hex_color: "#3986f7",
    money: "$117.73",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/idnemoamet.png?size=100x100&set=set1",
    name: "Roman Tyt",
    color: "Maroon",
    hex_color: "#903a67",
    money: "$132.30",
    mobile: "Android 8.0, Flyme UI",
  },
  {
    image: "https://robohash.org/voluptatumquifuga.png?size=100x100&set=set1",
    name: "Marjorie Kindell",
    color: "Maroon",
    hex_color: "#cefaf0",
    money: "$15.93",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/nobiscommodiet.png?size=100x100&set=set1",
    name: "Grover Swainston",
    color: "Mauv",
    hex_color: "#0a3dc9",
    money: "$526.96",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/dolorreprehenderiteos.png?size=100x100&set=set1",
    name: "Alyss Tommasuzzi",
    color: "Khaki",
    hex_color: "#8689ce",
    money: "$236.10",
    mobile: "Windows Mobile 6 Standard",
  },
  {
    image: "https://robohash.org/nonvoluptasperspiciatis.png?size=100x100&set=set1",
    name: "Linda Kagan",
    color: "Purple",
    hex_color: "#f13e4e",
    money: "$721.48",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/explicabovoluptatesrepellendus.png?size=100x100&set=set1",
    name: "Junia MacTerrelly",
    color: "Indigo",
    hex_color: "#a56c78",
    money: "$691.48",
    mobile: "Android 5.1, Sense UI 7",
  },
  {
    image: "https://robohash.org/dignissimosrerumsapiente.png?size=100x100&set=set1",
    name: "Starlene Steenson",
    color: "Purple",
    hex_color: "#d5e727",
    money: "$936.33",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/voluptateestquidem.png?size=100x100&set=set1",
    name: "Koo Coffelt",
    color: "Turquoise",
    hex_color: "#e51f31",
    money: "$415.69",
    mobile: "Android 2.3.4, up to 4.1, TouchWiz UI 4",
  },
  {
    image: "https://robohash.org/inestdoloremque.png?size=100x100&set=set1",
    name: "Carine Leinster",
    color: "Maroon",
    hex_color: "#168489",
    money: "$833.91",
    mobile: "Firefox OS",
  },
  {
    image: "https://robohash.org/placeatsintet.png?size=100x100&set=set1",
    name: "Con Dungay",
    color: "Indigo",
    hex_color: "#81cf14",
    money: "$592.15",
    mobile: "Android 2.3",
  },
  {
    image: "https://robohash.org/consequaturipsumnon.png?size=100x100&set=set1",
    name: "Welsh Williamson",
    color: "Teal",
    hex_color: "#a67a5c",
    money: "$700.36",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/seddoloremplaceat.png?size=100x100&set=set1",
    name: "Guglielmo Swindle",
    color: "Turquoise",
    hex_color: "#e01d66",
    money: "$43.63",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/consequaturoptioconsequatur.png?size=100x100&set=set1",
    name: "Dorie Yesenev",
    color: "Green",
    hex_color: "#3560c1",
    money: "$697.82",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/voluptatecorruptimolestiae.png?size=100x100&set=set1",
    name: "Louie Wanell",
    color: "Mauv",
    hex_color: "#79a08c",
    money: "$519.21",
    mobile: "Microsoft Windows Phone 7",
  },
];
